Explicitly query rank column on /points page
[2021-04-03 15:19:33,968] [ERROR  ] Unhandled exception
Traceback (most recent call last):
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pajlada/git/pajbot/pajbot/web/routes/base/points.py", line 41, in points
    rankings = db_session.query(User, "rank").from_statement(
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2055, in query
    return self._query_cls(entities, self, **kwargs)
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 174, in __init__
    self._set_entities(entities)
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 181, in _set_entities
    self._raw_columns = [
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 182, in <listcomp>
    coercions.expect(
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 175, in expect
    resolved = impl._literal_coercion(
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 375, in _literal_coercion
    return self._text_coercion(element, argname, **kw)
  File "/home/pajlada/git/pajbot/venv/lib/python3.9/site-packages/sqlalchemy/sql/coercions.py", line 808, in _text_coercion
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Textual column expression 'rank' should be explicitly declared with text('rank'), or use column('rank') for more specificity
[2021-04-03 15:19:33,991] [INFO   ] 127.0.0.1 - - [03/Apr/2021 15:19:33] "GET /points HTTP/1.1" 500 -